### ISSUE TITLE
SI units

### ISSUE THREAD

**Issue by orumayiru** [sonofeft/RocketProps#1]
not exactly an issue is it possible to use this for SI units.

**Comment by sonofeft** [comment]
Yes SI units can be used, however, property calls need to be wrapped in unit conversion calls.

from rocketprops.unit_conv_data import get_value
```
pObj = get_prop('hydrazine')
Thot  = get_value( TmaxC, 'degC', 'degR' )
SGhot = pObj.SGLiqAtTdegR( Thot )
```
For pressure:
```
P_Pa  = get_value( Ppsia, 'psia', 'Pa')
Ppsia = get_value( P_Pa, 'Pa', 'psia')
```
And for output, you can either do conversions yourself, or call get_value.
```
print('T = %g R = %g K'%( C.T, C.T/1.8 ))
print('SurfaceTension = %g lbf/in'%C.surf, ' = ', \
       get_value(C.surf, 'lbf/in', 'mN/m'), 'mN/m' )
```

**Comment by orumayiru** [comment]
I did the same, just modified all the rocket_prop functions  to give output in SI units. Thank you
